### ISSUE TITLE
Error when launching local development environment: missing public.pem and clientKey

### ISSUE THREAD

**Issue by YukiOnishi1129** [dailydotdev/daily-api#2362]
Hello, I'm setting up the local environment for daily-api to contribute to its OSS development, but I'm encountering the following error:

```

Error: ENOENT: no such file or directory, open '../apps/.cert/public.pem'
    at Object.openSync (node:fs:581:18)
    at Object.readFileSync (node:fs:457:35)
    at loadAuthKeys (/Users/xxx/xxx/xxx/daily-api/src/auth.ts:75:18)
    at plugin (/Users/xxx/xxx/xxx/daily-api/src/auth.ts:87:5)
    at Plugin.exec (/Users/xxx/xxx/xxx/daily-api/node_modules/avvio/lib/plugin.js:122:28)
    at Boot._loadPlugin (/Users/xxx/xxx/xxx/daily-api/node_modules/avvio/boot.js:423:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '../apps/.cert/public.pem'
}
[15:04:26.836] ERROR (77421): failed to load features
    err: {
      "type": "Error",
      "message": "Missing clientKey",
      "stack":
          Error: Missing clientKey
              at GrowthBook._refresh (/Users/xxx/xxx/xxx/daily-api/node_modules/@growthbook/growthbook/src/GrowthBook.ts:376:13)
              at GrowthBook.loadFeatures (/Users/xxx/xxx/xxx/daily-api/node_modules/@growthbook/growthbook/src/GrowthBook.ts:300:33)
              at loadFeatures (/Users/xxx/xxx/xxx/daily-api/src/growthbook.ts:47:14)
              at app (/Users/xxx/xxx/xxx/daily-api/src/index.ts:73:21)
              at processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async run (/Users/xxx/xxx/xxx/daily-api/bin/cli.ts:18:19)
    }
[nodemon] app crashed - waiting for file changes before starting...

```
The error occurs when I reach the last step of the following setup process:

1. docker-compose up -d
2. npm run db:migrate:latest
3. npm run db:seed:import
4. npm run dev

For setting up the local environment, I’m following the instructions here: https://github.com/dailydotdev/daily-api?tab=readme-ov-file#local-environment

Any guidance you could provide would be greatly appreciated.

**Comment by omBratteng** [comment]
You need to clone the [apps](https://github.com/dailydotdev/apps) repository as well, it contains the missing files
> path: '../apps/.cert/public.pem'

**Comment by YukiOnishi1129** [comment]
Thanks!
